# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 100

  - name: About Me
    url: about/
    weight: 200

  - name: Skills
    url: skill/
    weight: 300

  - name: Project
    url: project/
    weight: 400
  - parent: Project
    name: webRTC
    url: project/webrtc/
    weight: 410
  - parent: Project
    name: medicineChatBot
    url: project/medicinechatbot/
    weight: 420
  - parent: Project
    name: undeadsurvivor
    url: project/undeadsurvivor/
    weight: 430

  - name: Contact
    url: contact/
    weight: 500
  