# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 100

  - name: Resumé
    url: about/
    weight: 200

  - name: Projects
    url: projects/
    weight: 300
  - parent: Projects
    name: webRTC
    url: projects/webRTC
    weight: 310
  - parent: Projects
    name: medicineChatBot
    url: projects/medicineChatBot
    weight: 320
  - parent: Projects
    name: UniversityApp
    url: projects/UniversityApp
    weight: 330

  - name: Contact
    url: contact/
    weight: 400
  